version: '3.8'

services:
  nginx:
    build: 
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: lucasrmagalhaes/nginx
    container_name: nginx
    ports: 
      - "80:80"
    networks: 
      - production-network
    depends_on: 
      - "node1"
      - "node2"
      - "node3"
  
  mongodb:
    image: mongo
    container_name: mongodb
    networks: 
      - production-network

  node1:
    build:
      dockerfile: ./docker/node.dockerfile
      context: .
    image: lucasrmagalhaes/alura-books
    container_name: alura-books-1
    ports: 
      - "3000"
    networks: 
      - production-network
    depends_on: 
      - "mongodb"
  
  node2:
    build:
      dockerfile: ./docker/node.dockerfile
      context: .
    image: lucasrmagalhaes/alura-books
    container_name: alura-books-2
    ports: 
      - "3000"
    networks: 
      - production-network
    depends_on: 
      - "mongodb"
  
  node3:
    build:
      dockerfile: ./docker/node.dockerfile
      context: .
    image: lucasrmagalhaes/alura-books
    container_name: alura-books-3
    ports: 
      - "3000"
    networks: 
      - production-network
    depends_on: 
      - "mongodb"

networks:
  production-network:
    driver: bridge